export const DIALOGS_SET_ITEMS = 'DIALOGS:SET_ITEMS';
export const DIALOGS_SET_СURRENT_DIALOG_ID = 'DIALOGS:SET_СURRENT_DIALOG_ID';
export const DIALOGS_SET_LOADING = ' DIALOGS:SET_LOADING';
export const DIALOGS_SET_LAST_MESSAGE = ' DIALOGS:SET_LAST_MESSAGE';


export const MESSAGES_SET_ITEMS = 'MESSAGES:SET_ITEMS';
export const MESSAGES_SET_LOADING = 'MESSAGES:SET_LOADING';
export const MESSAGE_ADD_ITEM = 'MESSAGE:ADD_ITEM';
export const MESSAGE_REMOVE_ITEM = 'MESSAGE:REMOVE_ITEM';
export const MESSAGE_READ_ALL_MY = 'MESSAGE:READ_ALL_MY';
export const MESSAGE_READ_SENT_MSG = 'MESSAGE:READ_SENT_MSG';

export const USER_SET_IS_AUTH = 'USER:SET_IS_AUTH';
export const USER_SET_DATA = 'USER:SET_DATA';

export const ATTACHMENTS_ADD_FILE = 'ATTACHMENTS:ADD_FILE';
export const ATTACHMENTS_REMOVE_FILE = 'ATTACHMENTS:REMOVE_FILE';
export const ATTACHMENTS_ClEAR = 'ATTACHMENTS:CLEAR';