export const DIALOGS_SET_ITEMS = 'DIALOGS:SET_ITEMS';
export const DIALOGS_SET_СURRENT_DIALOG_ID = 'DIALOGS:SET_СURRENT_DIALOG_ID';
export const DIALOGS_SET_LOADING = ' DIALOGS:SET_LOADING';

export const MESSAGES_SET_ITEMS = 'MESSAGES:SET_ITEMS';
export const MESSAGES_SET_LOADING = 'MESSAGES:SET_LOADING';


export const USER_SET_DATA = 'USER:SET_DATA';
